sonar.projectKey=aws-etl-pipeline
sonar.projectName=AWS ETL Pipeline
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=lambda,glue-jobs,scripts
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/*.zip,**/dist/**,**/.venv/**,**/.aws-sam/**
sonar.python.version=3.9
